import { chromium } from "playwright";
const NA = "window.__nightaudit";
const browser = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--no-sandbox"] });
const p = await browser.newPage({ viewport: { width: 1280, height: 720 } });
p.on("pageerror", (e) => console.log("PAGEERROR:", e.message));
await p.goto("http://localhost:5199/?e2e=1&engine=webgl&seed=benchx&anomaly=none");
await p.waitForFunction(`(${NA}) && (${NA}).ready === true`, null, { timeout: 90000 });
await p.getByRole("button", { name: /BEGIN SHIFT/ }).click();
await p.waitForFunction(`(${NA}).state() === "playing"`, null, { timeout: 20000 });
await p.waitForTimeout(4500);
await p.evaluate(`${NA}.teleport(0.4, 0, 45.3)`);
await p.evaluate(`${NA}.look(-1.35, -0.12)`);
await p.waitForTimeout(400);
await p.screenshot({ path: ".tmp-a7-bench.png" });
await browser.close(); console.log("done");
