import { chromium } from 'playwright';
const b = await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader-webgl','--no-sandbox']});
const p = await b.newPage();
await p.goto('http://localhost:5199/?e2e=1&seed=tour&anomaly=none');
await p.click('text=BEGIN SHIFT');
await p.waitForFunction(() => window.__nightaudit?.loop?.() === 1, null, {timeout:20000});
await p.waitForTimeout(5700);
await p.evaluate(() => window.__nightaudit.teleport(0, 1.55, 10, Math.PI));
await p.waitForTimeout(600);
await p.screenshot({path:'/tmp/north-back.png'});
await p.evaluate(() => window.__nightaudit.teleport(-0.9, 1.55, 14, -Math.PI/2));
await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/sitter.png'});
await b.close();
console.log('done');
