import { chromium } from 'playwright';
const b = await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader-webgl','--no-sandbox']});
const p = await b.newPage();
await p.goto('http://localhost:5199/?e2e=1&seed=sf&anomaly=none');
await p.click('text=BEGIN SHIFT');
await p.waitForFunction(() => window.__nightaudit?.loop?.() === 1, null, {timeout:20000});
await p.waitForTimeout(5700);
await p.evaluate(() => { window.__nightaudit.teleport(0.4, 1.6, 39.5, Math.PI/2); window.__nightaudit.look(Math.PI/2, 0.08); });
await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/safety.png'});
await b.close();
console.log('done');
