import { chromium } from "@playwright/test";
import { writeFileSync } from "node:fs";
const b = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=swiftshader-webgl"] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
await p.goto("http://localhost:4177/?e2e=1&engine=webgl&seed=visual&quality=high");
await p.waitForFunction("window.__nightaudit && window.__nightaudit.ready === true", null, { timeout: 90000 });
await p.getByRole("button", { name: /BEGIN SHIFT/ }).click();
await p.waitForFunction("window.__nightaudit.state() === 'playing'");
await p.evaluate("window.__nightaudit.teleport(0, 0, 30)");
await p.waitForTimeout(1000);
const d2 = await p.evaluate("window.__nightaudit.screenshot()");
writeFileSync("/tmp/na-gallery.png", Buffer.from(d2.split(",")[1], "base64"));
await p.evaluate("window.__nightaudit.teleport(0, 0, 16)");
await p.waitForTimeout(600);
const d4 = await p.evaluate("window.__nightaudit.screenshot()");
writeFileSync("/tmp/na-records.png", Buffer.from(d4.split(",")[1], "base64"));
await b.close();
